using System.Collections.Generic;

namespace PrimoAutoEletrica.Services
{
    /// <summary>
    /// Chaves do gate final P0/P1 (PRIMOX-I18N-07) — fluxos críticos + empty/error operacionais.
    /// </summary>
    public partial class LocalizationService
    {
        internal static Dictionary<string, string> GatePt() => new()
        {
            ["StatusLabelFormat"] = "Status: {0}",
            ["QuoteStatusOpen"] = "Em aberto",
            ["QuoteStatusSent"] = "Enviado",
            ["QuoteStatusApproved"] = "Aprovado",
            ["QuoteStatusRejected"] = "Recusado",
            ["QuoteStatusExpired"] = "Vencido",
            ["QuoteStatusConvertedSale"] = "Convertido em venda",
            ["QuoteStatusConvertedOs"] = "Convertido em OS",
            ["VehiclesFoundOne"] = "1 veículo encontrado",
            ["VehiclesFoundFormat"] = "{0} veículos encontrados",
            ["HistoryWithOsAppointmentsFormat"] = "Histórico com {0} OS e {1} agendamento(s).",
            ["NoHistoryYet"] = "Sem histórico ainda.",
            ["QuoteNearExpiry"] = "Orçamento próximo do vencimento.",
            ["CartWithoutItems"] = "Carrinho sem itens.",
            ["OsConversionWithoutLink"] = "Conversão em OS sem vínculo persistido.",
            ["ClientQuoteEventsSummary"] = "Resumo do cliente e eventos do orçamento selecionado.",
            ["LastQuotes10"] = "Últimos 10 orçamentos",
            ["QuotesQuickPanelHint"] = "Painel rápido para revisar o histórico recente sem poluir a tela principal.",
            ["SeeAll"] = "Ver todos",
            ["NoItemsBelowMinimum"] = "Nenhum item abaixo do mínimo no momento.",
            ["NoProductsNearExpiry"] = "Nenhum produto próximo ao vencimento foi encontrado.",
            ["StockCardHint"] = "A ficha mostra identificação, estoque, preços, localização e fornecedor do item selecionado.",
            ["StockSearchHint"] = "Busca rápida por código, descrição, SKU ou código de barras. Duplo clique para editar.",
            ["EditProductTooltip"] = "Editar o produto selecionado na tabela",
            ["OpenStockAdjustTooltip"] = "Abrir ajuste de estoque",
            ["SelectProductToEdit"] = "Selecione um produto na tabela para editar.\n\nDica: clique em uma linha do estoque e depois em Editar produto, ou dê duplo clique diretamente na linha.",
            ["AgendaCentralSubtitle"] = "Central de compromissos operacionais — quem, quando, veículo, motivo, status e ações reais.",
            ["InactiveSuppliers"] = "Fornecedores inativos",
            ["SupplierManagementSubtitle"] = "Gestão completa de fornecedores e parceiros comerciais",
            ["DeleteSelectedSupplier"] = "Excluir fornecedor selecionado",
            ["CatalogTechnicalBase"] = "Base técnica de consulta importada de catálogos e fornecedores.",
            ["QuoteSentToPrint"] = "Orçamento enviado para impressão.",
            ["ClientNotFoundForEmail"] = "Cliente não localizado para envio de e-mail.",
            ["QuoteAlreadyApprovedOrConverted"] = "Este orçamento já está aprovado ou convertido.",
            ["QuoteAlreadyConvertedToSale"] = "Este orçamento já foi convertido em venda.",
            ["QuoteConvertedToSaleSuccess"] = "Orçamento convertido em venda com sucesso!",
            ["QuoteAlreadyHasLinkedOs"] = "Este orçamento já possui uma ordem de serviço vinculada.",
            ["QuoteConvertedToOsSuccess"] = "Orçamento convertido em OS com sucesso!",
            ["QuoteDeletedSuccess"] = "Orçamento excluído com sucesso!",
            ["QuotesModuleTitle"] = "Orçamentos",
            ["PdfGeneratedSuccessFormat"] = "PDF gerado com sucesso: {0}",
            ["PrintErrorFormat"] = "Erro ao imprimir: {0}",
            ["StockAdjustment"] = "Ajuste",
            ["StockEntry"] = "Entrada",
            ["StockExit"] = "Saída",
            ["QuotesAvailableFormat"] = "{0} orçamento(s) disponível(is) para selecionar e acompanhar antes de converter",
            ["VehiclePlateFormat"] = "Veículo: {0}",
            ["VehicleNotLinked"] = "Veículo não vinculado",
            ["VehicleNotInformed"] = "Veículo não informado",
            ["QuotesWalletTitle"] = "Carteira de orçamentos",
            ["FullWallet"] = "Carteira completa",
            ["SearchWithEmoji"] = "🔍 Buscar",
            ["OpenVehicleTechnicalRecord"] = "Abrir prontuário técnico do veículo",
            ["NoIdleProducts90Days"] = "Nenhum produto parado há 90 dias ou mais dentro do recorte atual.",
            ["NoOverdueTitlesOpen"] = "Nenhum título vencido em aberto até hoje."
        };

        internal static Dictionary<string, string> GateEn() => new()
        {
            ["StatusLabelFormat"] = "Status: {0}",
            ["QuoteStatusOpen"] = "Open",
            ["QuoteStatusSent"] = "Sent",
            ["QuoteStatusApproved"] = "Approved",
            ["QuoteStatusRejected"] = "Rejected",
            ["QuoteStatusExpired"] = "Expired",
            ["QuoteStatusConvertedSale"] = "Converted to sale",
            ["QuoteStatusConvertedOs"] = "Converted to work order",
            ["VehiclesFoundOne"] = "1 vehicle found",
            ["VehiclesFoundFormat"] = "{0} vehicles found",
            ["HistoryWithOsAppointmentsFormat"] = "History with {0} work order(s) and {1} appointment(s).",
            ["NoHistoryYet"] = "No history yet.",
            ["QuoteNearExpiry"] = "Quote nearing expiry.",
            ["CartWithoutItems"] = "Cart has no items.",
            ["OsConversionWithoutLink"] = "Converted to work order without a persisted link.",
            ["ClientQuoteEventsSummary"] = "Summary of the client and events for the selected quote.",
            ["LastQuotes10"] = "Last 10 quotes",
            ["QuotesQuickPanelHint"] = "Quick panel to review recent history without cluttering the main screen.",
            ["SeeAll"] = "See all",
            ["NoItemsBelowMinimum"] = "No items below minimum right now.",
            ["NoProductsNearExpiry"] = "No products near expiry were found.",
            ["StockCardHint"] = "The card shows identification, stock, prices, location, and supplier for the selected item.",
            ["StockSearchHint"] = "Quick search by code, description, SKU, or barcode. Double-click to edit.",
            ["EditProductTooltip"] = "Edit the product selected in the table",
            ["OpenStockAdjustTooltip"] = "Open stock adjustment",
            ["SelectProductToEdit"] = "Select a product in the table to edit.\n\nTip: click a stock row and then Edit product, or double-click the row.",
            ["AgendaCentralSubtitle"] = "Operational appointments hub — who, when, vehicle, reason, status, and real actions.",
            ["InactiveSuppliers"] = "Inactive suppliers",
            ["SupplierManagementSubtitle"] = "Full management of suppliers and commercial partners",
            ["DeleteSelectedSupplier"] = "Delete selected supplier",
            ["CatalogTechnicalBase"] = "Technical lookup base imported from catalogs and suppliers.",
            ["QuoteSentToPrint"] = "Quote sent to print.",
            ["ClientNotFoundForEmail"] = "Client not found for e-mail delivery.",
            ["QuoteAlreadyApprovedOrConverted"] = "This quote is already approved or converted.",
            ["QuoteAlreadyConvertedToSale"] = "This quote was already converted to a sale.",
            ["QuoteConvertedToSaleSuccess"] = "Quote converted to sale successfully!",
            ["QuoteAlreadyHasLinkedOs"] = "This quote already has a linked work order.",
            ["QuoteConvertedToOsSuccess"] = "Quote converted to work order successfully!",
            ["QuoteDeletedSuccess"] = "Quote deleted successfully!",
            ["QuotesModuleTitle"] = "Quotes",
            ["PdfGeneratedSuccessFormat"] = "PDF generated successfully: {0}",
            ["PrintErrorFormat"] = "Print error: {0}",
            ["StockAdjustment"] = "Adjust",
            ["StockEntry"] = "Inbound",
            ["StockExit"] = "Outbound",
            ["QuotesAvailableFormat"] = "{0} quote(s) available to select and track before converting",
            ["VehiclePlateFormat"] = "Vehicle: {0}",
            ["VehicleNotLinked"] = "Vehicle not linked",
            ["VehicleNotInformed"] = "Vehicle not provided",
            ["QuotesWalletTitle"] = "Quotes wallet",
            ["FullWallet"] = "Full wallet",
            ["SearchWithEmoji"] = "🔍 Search",
            ["OpenVehicleTechnicalRecord"] = "Open vehicle technical record",
            ["NoIdleProducts90Days"] = "No products idle for 90+ days in the current slice.",
            ["NoOverdueTitlesOpen"] = "No overdue open titles through today."
        };

        internal static Dictionary<string, string> GateEs() => new()
        {
            ["StatusLabelFormat"] = "Estado: {0}",
            ["QuoteStatusOpen"] = "Abierto",
            ["QuoteStatusSent"] = "Enviado",
            ["QuoteStatusApproved"] = "Aprobado",
            ["QuoteStatusRejected"] = "Rechazado",
            ["QuoteStatusExpired"] = "Vencido",
            ["QuoteStatusConvertedSale"] = "Convertido en venta",
            ["QuoteStatusConvertedOs"] = "Convertido en OT",
            ["VehiclesFoundOne"] = "1 vehículo encontrado",
            ["VehiclesFoundFormat"] = "{0} vehículos encontrados",
            ["HistoryWithOsAppointmentsFormat"] = "Historial con {0} OT y {1} cita(s).",
            ["NoHistoryYet"] = "Sin historial aún.",
            ["QuoteNearExpiry"] = "Presupuesto próximo del vencimiento.",
            ["CartWithoutItems"] = "Carrito sin ítems.",
            ["OsConversionWithoutLink"] = "Conversión a OT sin vínculo persistido.",
            ["ClientQuoteEventsSummary"] = "Resumen del cliente y eventos del presupuesto seleccionado.",
            ["LastQuotes10"] = "Últimos 10 presupuestos",
            ["QuotesQuickPanelHint"] = "Panel rápido para revisar el historial reciente sin saturar la pantalla principal.",
            ["SeeAll"] = "Ver todos",
            ["NoItemsBelowMinimum"] = "Ningún ítem por debajo del mínimo en este momento.",
            ["NoProductsNearExpiry"] = "No se encontraron productos próximos al vencimiento.",
            ["StockCardHint"] = "La ficha muestra identificación, inventario, precios, ubicación y proveedor del ítem seleccionado.",
            ["StockSearchHint"] = "Búsqueda rápida por código, descripción, SKU o código de barras. Doble clic para editar.",
            ["EditProductTooltip"] = "Editar el producto seleccionado en la tabla",
            ["OpenStockAdjustTooltip"] = "Abrir ajuste de inventario",
            ["SelectProductToEdit"] = "Seleccione un producto en la tabla para editar.\n\nConsejo: haga clic en una fila y luego en Editar producto, o haga doble clic en la fila.",
            ["AgendaCentralSubtitle"] = "Central de compromisos operativos — quién, cuándo, vehículo, motivo, estado y acciones reales.",
            ["InactiveSuppliers"] = "Proveedores inactivos",
            ["SupplierManagementSubtitle"] = "Gestión completa de proveedores y socios comerciales",
            ["DeleteSelectedSupplier"] = "Eliminar proveedor seleccionado",
            ["CatalogTechnicalBase"] = "Base técnica de consulta importada de catálogos y proveedores.",
            ["QuoteSentToPrint"] = "Presupuesto enviado a impresión.",
            ["ClientNotFoundForEmail"] = "Cliente no localizado para el envío de correo.",
            ["QuoteAlreadyApprovedOrConverted"] = "Este presupuesto ya está aprobado o convertido.",
            ["QuoteAlreadyConvertedToSale"] = "Este presupuesto ya fue convertido en venta.",
            ["QuoteConvertedToSaleSuccess"] = "¡Presupuesto convertido en venta correctamente!",
            ["QuoteAlreadyHasLinkedOs"] = "Este presupuesto ya tiene una orden de trabajo vinculada.",
            ["QuoteConvertedToOsSuccess"] = "¡Presupuesto convertido en OT correctamente!",
            ["QuoteDeletedSuccess"] = "¡Presupuesto eliminado correctamente!",
            ["QuotesModuleTitle"] = "Presupuestos",
            ["PdfGeneratedSuccessFormat"] = "PDF generado correctamente: {0}",
            ["PrintErrorFormat"] = "Error al imprimir: {0}",
            ["StockAdjustment"] = "Ajuste",
            ["StockEntry"] = "Entrada",
            ["StockExit"] = "Salida",
            ["QuotesAvailableFormat"] = "{0} presupuesto(s) disponible(s) para seleccionar y seguir antes de convertir",
            ["VehiclePlateFormat"] = "Vehículo: {0}",
            ["VehicleNotLinked"] = "Vehículo no vinculado",
            ["VehicleNotInformed"] = "Vehículo no informado",
            ["QuotesWalletTitle"] = "Cartera de presupuestos",
            ["FullWallet"] = "Cartera completa",
            ["SearchWithEmoji"] = "🔍 Buscar",
            ["OpenVehicleTechnicalRecord"] = "Abrir ficha técnica del vehículo",
            ["NoIdleProducts90Days"] = "Ningún producto parado hace 90 días o más en el recorte actual.",
            ["NoOverdueTitlesOpen"] = "Ningún título vencido en abierto hasta hoy."
        };
    }
}
