<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0;net6.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>PRIMOX.Infrastructure</RootNamespace>
    <AssemblyName>PRIMOX.Infrastructure</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="2.1.13" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net10.0'">
    <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net6.0'">
    <PackageReference Include="Microsoft.Data.Sqlite" Version="7.0.20" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PRIMOX.Domain\PRIMOX.Domain.csproj" />
    <ProjectReference Include="..\PRIMOX.Application\PRIMOX.Application.csproj" />
  </ItemGroup>

</Project>
