import os
import csv

def generate_b1_docs():
    os.makedirs("Docs/audit/2026-09-20", exist_ok=True)
    
    # ----------------------------------------------------
    # 1. B1_PRODUCT_DISCOVERY_MATRIX.csv
    # ----------------------------------------------------
    matrix_rows = [
        # Module,Feature,UI,ViewModel,Service,Repository,Database,Persistence,API,Integration,UnitTest,IntegrationTest,UITest,Light,Dark,RBAC,Status,Evidence,Risk,NextAction
        ["Dashboard", "Visao Geral & KPIs", "DashboardControl.xaml", "DashboardViewModel", "DatabaseService", "NOT FOUND", "Orcamentos, OrdensServico, MovimentacoesFinanceiras", "REAL", "PARTIAL", "REAL", "PASS", "PASS", "PASS", "PASS", "PASS", "PASS", "CORE", "UserControls/DashboardControl.xaml, ViewModels/DashboardViewModel.cs", "LOW", "Manter e atualizar novos indicadores"],
        ["Clientes", "Cadastro & Edicao de Clientes", "ClientesControl.xaml, NovoClienteWindow.xaml, EditarClienteWindow.xaml", "ClientesViewModel", "CustomerService", "ClienteRepository", "Clientes", "REAL", "NOT_IMPLEMENTED", "REAL", "PASS", "PASS", "PASS", "PASS", "PASS", "PASS", "CORE", "Views/Clientes/*, Repositories/ClienteRepository.cs", "LOW", "Manter"],
        ["Clientes", "Historico & Visualizacao do Cliente", "VisualizarClienteWindow.xaml, HistoricoClienteWindow.xaml", "ClientesViewModel", "Primox360Service", "ClienteRepository", "Clientes", "REAL", "NOT_IMPLEMENTED", "REAL", "PASS", "PASS", "PASS", "PASS", "PASS", "PASS", "CORE", "Views/Clientes/VisualizarClienteWindow.xaml, Services/Primox360Service.cs", "LOW", "Manter"],
        ["Clientes", "Gestao de Consentimento LGPD", "VisualizarClienteWindow.xaml, HistoricoClienteWindow.xaml", "ClientesViewModel", "ClienteRepository", "ClienteRepository", "Clientes (ConsentimentoLGPD)", "REAL", "NOT_IMPLEMENTED", "REAL", "PASS", "PASS", "PASS", "PASS", "PASS", "PASS", "CORE", "Clientes table column ConsentimentoLGPD, Repositories/ClienteRepository.cs", "LOW", "Manter"],
        ["Veiculos", "Cadastro & Edicao de Veiculos", "VeiculosControl.xaml, NovoVeiculoWindow.xaml", "VeiculosViewModel", "VeiculoProfileService", "ClienteRepository", "Veiculos", "REAL", "NOT_IMPLEMENTED", "REAL", "PASS", "PASS", "PASS", "PASS", "PASS", "PASS", "CORE", "UserControls/VeiculosControl.xaml, Views/NovoVeiculoWindow.xaml", "LOW", "Manter"],
        ["Veiculos", "Prontuario & Telemetria Eletrica Veicular", "VisualizarVeiculoWindow.xaml, NovoVeiculoWindow.xaml", "VeiculosViewModel", "AutoEletricaTecnicaService", "ClienteRepository", "Veiculos (BateriaPrincipal, Alternador, Testes)", "REAL", "NOT_IMPLEMENTED", "REAL", "PASS", "PASS", "PASS", "PASS", "PASS", "PASS", "CORE", "Veiculos table has 49 columns including electrical telemetry", "LOW", "Manter"],
        ["Cliente 360", "Visao Unificada 360 do Cliente por ID", "HistoricoClienteWindow.xaml", "ClientesViewModel", "Primox360Service", "ClienteRepository, OrdemServicoRepository", "Clientes, Veiculos, OrdensServico, Orcamentos, ContasReceber", "REAL", "NOT_IMPLEMENTED", "REAL", "PASS", "PASS", "PASS", "PASS", "PASS", "PASS", "CORE", "Services/Primox360Service.cs:ObterCliente360", "LOW", "Manter"],
        ["Cliente 360", "Integracao WhatsApp com Validacao LGPD", "HistoricoClienteWindow.xaml", "ClientesViewModel", "CommercialDocumentActions", "ClienteRepository", "Clientes", "REAL", "NOT_IMPLEMENTED", "PARTIAL", "PASS", "PASS", "PASS", "PASS", "PASS", "PASS", "PARTIAL", "HistoricoClienteWindow.xaml.cs:WhatsApp360Button_Click (wa.me link)", "LOW", "Conectar gateway WhatsApp oficial em fase futura"],
        ["Vehicle 360", "Visao Unificada 360 do Veiculo por ID", "VisualizarVeiculoWindow.xaml", "VeiculosViewModel", "Primox360Service", "ClienteRepository, OrdemServicoRepository", "Veiculos, OrdensServico, Orcamentos", "REAL", "NOT_IMPLEMENTED", "REAL", "PASS", "PASS", "PASS", "PASS", "PASS", "PASS", "CORE", "Services/Primox360Service.cs:ObterVeiculo360, VisualizarVeiculoWindow.xaml.cs", "LOW", "Manter"],
        ["Orçamentos", "Criacao, Edicao e Calculo de Orcamento", "OrcamentosControl.xaml, NovoOrcamentoWindow.xaml", "OrcamentosViewModel", "OrcamentoDatabaseService", "NOT FOUND", "Orcamentos, OrcamentoItens", "REAL", "CORE", "REAL", "PASS", "PASS", "PASS", "PASS", "PASS", "PASS", "CORE", "Services/OrcamentoDatabaseService.cs, UserControls/OrcamentosControl.xaml", "LOW", "Manter"],
        ["Orçamentos", "Aprovacao & Tokens de Aprovacao", "OrcamentosControl.xaml, NovoOrcamentoWindow.xaml", "OrcamentosViewModel", "OrcamentoAprovacaoService", "NOT FOUND", "Orcamentos", "REAL", "CORE", "REAL", "PASS", "PASS", "PASS", "PASS", "PASS", "PASS", "CORE", "Services/OrcamentoAprovacaoService.cs", "LOW", "Manter"],
        ["Orçamentos", "Conversao Direta em Ordem de Servico", "OrcamentosControl.xaml", "OrcamentosViewModel", "OrcamentoDatabaseService", "OrdemServicoRepository", "Orcamentos, OrdensServico, OrdemServicoItens", "REAL", "NOT_IMPLEMENTED", "REAL", "PASS", "PASS", "PASS", "PASS", "PASS", "PASS", "CORE", "OrcamentosViewModel.cs:ConverterEmOrdemServico", "LOW", "Manter"],
        ["Orçamentos", "Botao Enviar Email", "OrcamentosView.xaml", "OrcamentosViewModel", "NOT FOUND", "NOT FOUND", "NOT FOUND", "NOT FOUND", "NOT_IMPLEMENTED", "NOT_IMPLEMENTED", "NOT TESTED", "NOT TESTED", "FAIL", "PASS", "PASS", "NOT FOUND", "UI_ONLY", "Views/OrcamentosView.xaml:73 (Button Email sem click/command)", "LOW", "Implementar servico SMTP ou remover botao"],
        ["Orçamentos", "Botao Converter em Venda Balcao", "OrcamentosView.xaml", "OrcamentosViewModel", "NOT FOUND", "NOT FOUND", "NOT FOUND", "NOT FOUND", "NOT_IMPLEMENTED", "NOT_IMPLEMENTED", "NOT TESTED", "NOT TESTED", "FAIL", "PASS", "PASS", "NOT FOUND", "UI_ONLY", "Views/OrcamentosView.xaml:76 (Button sem click/command)", "LOW", "Conectar ao PDV/VendaRepository"],
        ["DVI", "Checklist Entrada/Saida e Fotos", "DviOrcamentoWindow.xaml, OrdemServicoWindow.xaml", "NOT FOUND", "DviChecklistService", "NOT FOUND", "JSON Files (os-{id}.json, orc-{id}.json)", "PARTIAL", "NOT_IMPLEMENTED", "REAL", "PASS", "PASS", "PASS", "PASS", "PASS", "PASS", "PARTIAL", "Services/DviChecklistService.cs (persistencia em AppData/Dvi JSON)", "MEDIUM", "Migrar documento DVI para tabela SQLite se relacional for exigido"],
        ["DVI", "Aprovacao Remota Online / Portal Cliente", "NOT FOUND", "NOT FOUND", "NOT FOUND", "NOT FOUND", "NOT FOUND", "NOT FOUND", "NOT_IMPLEMENTED", "NOT_IMPLEMENTED", "NOT TESTED", "NOT TESTED", "NOT TESTED", "NOT_APPLICABLE", "NOT_APPLICABLE", "NOT FOUND", "NOT_IMPLEMENTED", "Sem portal web externo ou cloud sync", "MEDIUM", "Planejar arquitetura Cloud/Portal na Trilha B"],
        ["Ordens de Serviço", "Abertura, Edicao e Execucao de OS", "OrdensServicoControl.xaml, OrdemServicoWindow.xaml", "OrdensServicoViewModel", "DatabaseService", "OrdemServicoRepository", "OrdensServico, OrdemServicoItens, OrdemServicoEventos", "REAL", "NOT_IMPLEMENTED", "REAL", "PASS", "PASS", "PASS", "PASS", "PASS", "PASS", "CORE", "Repositories/OrdemServicoRepository.cs, UserControls/OrdensServicoControl.xaml", "LOW", "Manter"],
        ["Ordens de Serviço", "Baixa Automatica de Estoque ao Finalizar OS", "OrdemServicoWindow.xaml", "OrdensServicoViewModel", "DatabaseService", "OrdemServicoRepository", "Produtos, OrdensServico", "REAL", "NOT_IMPLEMENTED", "REAL", "PASS", "PASS", "PASS", "PASS", "PASS", "PASS", "CORE", "OrdemServicoRepository.cs:StatusDeveBaixarEstoque", "LOW", "Manter"],
        ["Ordens de Serviço", "Integracao Financeira / Gerar Receita", "OrdensServicoControl.xaml", "OrdensServicoViewModel", "FinanceiroDatabaseService", "OrdemServicoRepository", "ContasReceber, MovimentacoesFinanceiras", "REAL", "NOT_IMPLEMENTED", "REAL", "PASS", "PASS", "PASS", "PASS", "PASS", "PASS", "CORE", "FinanceiroDatabaseService.cs:RegistrarReceitaOrdemServicoIntegrada", "LOW", "Manter"],
        ["Autoelétrica Técnica", "Prontuario Eletrico Estruturado", "AutoEletricaTecnicaControl.xaml, VisualizarVeiculoWindow.xaml", "AutoEletricaTecnicaViewModel", "AutoEletricaTecnicaService", "ClienteRepository", "Veiculos", "REAL", "NOT_IMPLEMENTED", "REAL", "PASS", "PASS", "PASS", "PASS", "PASS", "PASS", "CORE", "Services/AutoEletricaTecnicaService.cs:CriarProntuario", "LOW", "Manter"],
        ["Autoelétrica Técnica", "Roteiros de Diagnostico Eletrico", "AutoEletricaTecnicaControl.xaml", "AutoEletricaTecnicaViewModel", "AutoEletricaTecnicaService", "NOT FOUND", "In-Memory Catalog (D01-D06)", "MOCK", "NOT_IMPLEMENTED", "PARTIAL", "PASS", "PASS", "PASS", "PASS", "PASS", "PASS", "PARTIAL", "AutoEletricaTecnicaService.cs:ObterRoteirosDiagnostico (catalogo fixo em codigo)", "MEDIUM", "Criar tabela de catalogo de roteiros no banco"],
        ["Autoelétrica Técnica", "Persistencia de Resultados de Diagnostico", "AutoEletricaTecnicaControl.xaml", "AutoEletricaTecnicaViewModel", "AutoEletricaRoteiroPersistService", "NOT FOUND", "JSON File (roteiros-resultados.json)", "PARTIAL", "NOT_IMPLEMENTED", "PARTIAL", "PASS", "PASS", "PASS", "PASS", "PASS", "PASS", "PARTIAL", "AutoEletricaRoteiroPersistService.cs (salva por Codigo, sem vinculo OS/Veiculo)", "HIGH", "Vincular resultado a OrdemServicoId e VeiculoId"],
        ["Histórico Técnico", "Historico Estruturado de Defeitos e Servicos", "AutoEletricaTecnicaControl.xaml, VisualizarVeiculoWindow.xaml", "AutoEletricaTecnicaViewModel", "SintomaCausaHistoricoService", "OrdemServicoRepository", "OrdensServico, OrdemServicoItens", "REAL", "NOT_IMPLEMENTED", "REAL", "PASS", "PASS", "PASS", "PASS", "PASS", "PASS", "CORE", "Services/SintomaCausaHistoricoService.cs", "LOW", "Manter"],
        ["Estoque", "Cadastro & Gestao de Produtos", "EstoqueControl.xaml, NovoProdutoWindow.xaml, EditarProdutoWindow.xaml", "NOT FOUND", "EstoqueOperationalService", "ProdutoRepository", "Produtos", "REAL", "CORE", "REAL", "PASS", "PASS", "PASS", "PASS", "PASS", "PASS", "CORE", "UserControls/EstoqueControl.xaml, Repositories/ProdutoRepository.cs", "LOW", "Manter"],
        ["Estoque", "Ajustes de Estoque & Historico", "AjusteEstoqueWindow.xaml, HistoricoEstoqueWindow.xaml", "NOT FOUND", "EstoqueOperationalService", "ProdutoRepository", "Produtos", "REAL", "CORE", "REAL", "PASS", "PASS", "PASS", "PASS", "PASS", "PASS", "CORE", "Views/AjusteEstoqueWindow.xaml, Repositories/ProdutoRepository.cs", "LOW", "Manter"],
        ["Estoque", "Catalogo Master de Pecas & Aplicacoes", "CatalogoPecasControl.xaml, RevisarCatalogoPecaWindow.xaml", "CatalogoPecasViewModel", "CatalogoPecasService", "NOT FOUND", "CatalogoPecas, CatalogoPecaVeiculos, CatalogoVeiculos", "REAL", "NOT_IMPLEMENTED", "REAL", "PASS", "PASS", "PASS", "PASS", "PASS", "PASS", "CORE", "4.287 pecas, 51.119 aplicacoes veiculo-peca no banco", "LOW", "Manter"],
        ["Estoque", "Importacao de Catalogos Fornecedores PDF/CSV", "ImportarCatalogoPecasWindow.xaml", "CatalogoPecasViewModel", "CatalogoImportacaoService", "NOT FOUND", "CatalogoImportacoes, CatalogoImportacaoErros", "REAL", "NOT_IMPLEMENTED", "REAL", "PASS", "PASS", "PASS", "PASS", "PASS", "PASS", "CORE", "Services/CatalogoImportacaoService.cs", "LOW", "Manter"],
        ["Estoque", "Transferencia entre Filiais", "TransferirEstoqueWindow.xaml", "NOT FOUND", "NOT FOUND", "NOT FOUND", "Filiais (0 rows)", "NOT FOUND", "NOT_IMPLEMENTED", "NOT_IMPLEMENTED", "NOT TESTED", "NOT TESTED", "FAIL", "PASS", "PASS", "NOT FOUND", "UI_ONLY", "Views/TransferirEstoqueWindow.xaml (39 linhas, sem fluxo)", "MEDIUM", "Implementar servico de filiais ou desativar"],
        ["Financeiro", "Contas a Pagar", "FinanceiroControl.xaml", "FinanceiroViewModel", "FinanceiroDatabaseService", "NOT FOUND", "ContasPagar", "REAL", "NOT_IMPLEMENTED", "REAL", "PASS", "PASS", "PASS", "PASS", "PASS", "PASS", "CORE", "UserControls/FinanceiroControl.xaml, Services/FinanceiroDatabaseService.cs", "MEDIUM", "Adicionar FornecedorId em ContasPagar (RISK - IDENTITY ASSOCIATION)"],
        ["Financeiro", "Contas a Receber", "FinanceiroControl.xaml", "FinanceiroViewModel", "FinanceiroDatabaseService", "NOT FOUND", "ContasReceber", "REAL", "NOT_IMPLEMENTED", "REAL", "PASS", "PASS", "PASS", "PASS", "PASS", "PASS", "CORE", "UserControls/FinanceiroControl.xaml, Services/FinanceiroDatabaseService.cs", "LOW", "Manter"],
        ["Financeiro", "Movimentacoes & Fluxo de Caixa", "FinanceiroControl.xaml", "FinanceiroViewModel", "FinanceiroDatabaseService", "NOT FOUND", "MovimentacoesFinanceiras", "REAL", "CORE", "REAL", "PASS", "PASS", "PASS", "PASS", "PASS", "PASS", "CORE", "Services/FinanceiroDatabaseService.cs", "LOW", "Manter"],
        ["Caixa", "Operacoes de Caixa (Abertura/Fechamento/Sangria/Suprimento)", "OperacaoCaixaWindow.xaml", "PDVViewModel", "CaixaService", "NOT FOUND", "CaixaSessoes, MovimentacoesCaixa", "REAL", "NOT_IMPLEMENTED", "REAL", "PASS", "PASS", "PASS", "PASS", "PASS", "PASS", "CORE", "Views/OperacaoCaixaWindow.xaml, Services/CaixaService.cs", "LOW", "Manter"],
        ["Vendas", "Frente de Caixa PDV & Pagamento Misto", "PDVControl.xaml, PagamentoMistoWindow.xaml", "PDVViewModel", "VendaRepository", "VendaRepository", "Vendas, VendaItens", "REAL", "NOT_IMPLEMENTED", "REAL", "PASS", "PASS", "PASS", "PASS", "PASS", "PASS", "CORE", "UserControls/PDVControl.xaml, Repositories/VendaRepository.cs", "LOW", "Manter"],
        ["Relatórios", "Relatorios Operacionais & Comerciais", "RelatoriosControl.xaml", "RelatoriosViewModel", "RelatorioService", "NOT FOUND", "OrdensServico, Orcamentos, Vendas, Produtos", "REAL", "NOT_IMPLEMENTED", "REAL", "PASS", "PASS", "PASS", "PASS", "PASS", "PASS", "CORE", "UserControls/RelatoriosControl.xaml, Services/RelatorioService.cs", "LOW", "Manter"],
        ["Relatórios", "Exportacao Contabil SPED", "RelatoriosControl.xaml", "RelatoriosViewModel", "ContabilExportService", "NOT FOUND", "NOT FOUND", "REAL", "NOT_IMPLEMENTED", "REAL", "PASS", "PASS", "PASS", "PASS", "PASS", "PASS", "PARTIAL", "Services/ContabilExportService.cs:120 (TODO: SPED completo)", "MEDIUM", "Completar layout oficial SPED"],
        ["Fiscal", "Emissao NF-e Homologacao (Modelo 55)", "FiscalOperationsControl.xaml", "NOT FOUND", "FiscalOperationsCenterService, NFeHomologationService", "NOT FOUND", "FiscalDocuments, FiscalOperations, FiscalEvents", "REAL", "NOT_IMPLEMENTED", "PARTIAL", "PASS", "PASS", "PASS", "PASS", "PASS", "PASS", "PARTIAL", "Services/Fiscal/NFeHomologationService.cs (Focus/PlugNotas)", "MEDIUM", "Manter em homologacao"],
        ["Fiscal", "Emissao NF-e Producao SEFAZ", "FiscalOperationsControl.xaml", "NOT FOUND", "FiscalProductionGuard", "NOT FOUND", "NOT FOUND", "NOT FOUND", "NOT_IMPLEMENTED", "EXTERNAL_DEPENDENCY", "PASS", "PASS", "PASS", "PASS", "PASS", "PASS", "EXTERNAL_DEPENDENCY", "Services/Fiscal/FiscalProductionGuard.cs (bloqueio intencional)", "HIGH", "Liberar producao apos contratacao do provedor"],
        ["Fiscal", "Importacao de XML NF-e Entrada", "ImportarNFeControl.xaml, ImportarNotaWindow.xaml", "NOT FOUND", "NFeImportacaoService", "NOT FOUND", "ImportacoesNFe, ImportacoesItens", "REAL", "NOT_IMPLEMENTED", "REAL", "PASS", "PASS", "PASS", "PASS", "PASS", "PASS", "CORE", "UserControls/ImportarNFeControl.xaml, Services/NFeImportacaoService.cs", "LOW", "Manter"],
        ["Fiscal", "Geracao DANFE Informativo PDF", "FiscalOperationsControl.xaml", "NOT FOUND", "DanfeInformationalPdfGenerator", "NOT FOUND", "FiscalDocuments", "REAL", "NOT_IMPLEMENTED", "REAL", "PASS", "PASS", "PASS", "PASS", "PASS", "PASS", "CORE", "Services/Fiscal/DanfeInformationalPdfGenerator.cs", "LOW", "Manter"],
        ["Agenda", "Agendamentos & Timeline da Oficina", "AgendamentosControl.xaml, NovoAgendamentoPremiumWindow.xaml", "AgendamentosViewModel", "AgendamentoDatabaseService", "NOT FOUND", "Agendamentos, AgendamentoTimeline, AgendamentoProdutos, AgendamentoServicos", "REAL", "NOT_IMPLEMENTED", "REAL", "PASS", "PASS", "PASS", "PASS", "PASS", "PASS", "CORE", "UserControls/AgendamentosControl.xaml, Services/AgendamentoDatabaseService.cs", "LOW", "Manter"],
        ["Agenda", "Conversao de Agendamento em OS", "AgendamentosControl.xaml", "AgendamentosViewModel", "AgendamentoDatabaseService", "OrdemServicoRepository", "Agendamentos, OrdensServico", "REAL", "NOT_IMPLEMENTED", "REAL", "PASS", "PASS", "PASS", "PASS", "PASS", "PASS", "CORE", "AgendamentosViewModel.cs:ConverterEmOrdemServico", "LOW", "Manter"],
        ["Funcionários", "Gestao de Equipe, Cargos & 2FA TOTP", "FuncionariosControl.xaml, NovoFuncionarioWindow.xaml, TwoFactorSetupWindow.xaml", "NOT FOUND", "TwoFactorService", "FuncionarioRepository", "Funcionarios", "REAL", "NOT_IMPLEMENTED", "REAL", "PASS", "PASS", "PASS", "PASS", "PASS", "PASS", "CORE", "Repositories/FuncionarioRepository.cs, Views/TwoFactorSetupWindow.xaml", "LOW", "Manter"],
        ["Configurações", "Parametros do Sistema & Oficina", "ConfiguracoesSistemaWindow.xaml", "NOT FOUND", "ConfiguracoesSistemaService", "NOT FOUND", "ConfiguracoesSistema", "REAL", "NOT_IMPLEMENTED", "REAL", "PASS", "PASS", "PASS", "PASS", "PASS", "PASS", "CORE", "Views/ConfiguracoesSistemaWindow.xaml, 25 configuracoes no banco", "LOW", "Manter"],
        ["Backup / Restore", "Backup Automatico, Manual & Restore com Validacao", "BackupSettingsWindow.xaml, ConfiguracoesSistemaWindow.xaml", "NOT FOUND", "DatabaseBackupService", "NOT FOUND", "DatabaseBackups", "REAL", "NOT_IMPLEMENTED", "REAL", "PASS", "PASS", "PASS", "PASS", "PASS", "PASS", "CORE", "Services/DatabaseBackupService.cs (Jail enforcement, integridade, pool clear)", "LOW", "Manter"],
        ["Auditoria", "Trilha de Auditoria & Registro de Acoes Criticas", "ConfiguracoesSistemaWindow.xaml", "NOT FOUND", "AuditLogService", "AuditoriaRepository", "AuditLogs", "REAL", "NOT_IMPLEMENTED", "REAL", "PASS", "PASS", "PASS", "PASS", "PASS", "PASS", "CORE", "Services/AuditLogService.cs, 1.592 registros em AuditLogs", "LOW", "Manter"],
        ["RBAC", "Perfis & Permissoes de Acesso", "ConfigurarPermissoesWindow.xaml, GerenciarPerfisWindow.xaml, NovoPerfilWindow.xaml", "NOT FOUND", "PermissionService", "NOT FOUND", "PerfisAcesso, Permissoes, PerfilPermissoes", "REAL", "NOT_IMPLEMENTED", "REAL", "PASS", "PASS", "PASS", "PASS", "PASS", "PASS", "CORE", "10 perfis, 82 permissoes cadastradas no banco", "LOW", "Corrigir duplicidade de encoding Mecanico/Mecânico"],
        ["Licenciamento", "Licenciamento Local JSON + SHA-256", "LicenseActivationWindow.xaml", "NOT FOUND", "LicenseService", "NOT FOUND", "JSON File (licenca local)", "MOCK", "NOT_IMPLEMENTED", "NOT_IMPLEMENTED", "PASS", "PASS", "PASS", "PASS", "PASS", "PASS", "MOCK", "Services/LicenseService.cs:13 (IsCommercialScaffoldOnly = true)", "HIGH", "Implementar servidor de licencas RSA/ECDSA para distribuicao comercial"],
        ["Licenciamento", "Licenciamento Servidor / SaaS Online", "NOT FOUND", "NOT FOUND", "NOT FOUND", "NOT FOUND", "NOT FOUND", "NOT FOUND", "NOT_IMPLEMENTED", "NOT_IMPLEMENTED", "NOT TESTED", "NOT TESTED", "NOT TESTED", "NOT_APPLICABLE", "NOT_APPLICABLE", "NOT FOUND", "NOT_IMPLEMENTED", "Nao existe servidor de licenca conectado", "HIGH", "Definir arquitetura comercial de licenciamento"],
        ["API REST", "Endpoints Publicos & Autenticacao JWT", "Program.cs (Api)", "NOT FOUND", "Microsoft.AspNetCore", "NOT FOUND", "NOT FOUND", "REAL", "CORE", "REAL", "PASS", "PASS", "PASS", "NOT_APPLICABLE", "NOT_APPLICABLE", "PASS", "CORE", "PrimoAutoEletrica.Api/Program.cs (GET /api/health, POST /api/auth/token)", "LOW", "Manter"],
        ["API REST", "Endpoints de Orcamentos & Estoque", "Program.cs (Api)", "NOT FOUND", "OrcamentoDatabaseService, ProdutoRepository", "ProdutoRepository", "Orcamentos, Produtos", "REAL", "CORE", "REAL", "PASS", "PASS", "PASS", "NOT_APPLICABLE", "NOT_APPLICABLE", "PASS", "CORE", "Endpoints /api/orcamentos, /api/estoque/produtos", "LOW", "Manter"],
        ["API REST", "Endpoints de OS, Clientes, Veiculos, Fiscal", "NOT FOUND", "NOT FOUND", "NOT FOUND", "NOT FOUND", "NOT FOUND", "NOT FOUND", "NOT_IMPLEMENTED", "NOT_IMPLEMENTED", "NOT TESTED", "NOT TESTED", "NOT TESTED", "NOT_APPLICABLE", "NOT_APPLICABLE", "NOT FOUND", "NOT_IMPLEMENTED", "Endpoints nao mapeados em Program.cs", "MEDIUM", "Criar endpoints REST para OS, Clientes e Veiculos"],
        ["Integrações Externas", "WhatsApp Link (wa.me) & PDF", "VisualizarClienteWindow.xaml, NovoOrcamentoWindow.xaml", "OrcamentosViewModel", "CommercialDocumentActions", "NOT FOUND", "NOT FOUND", "NOT FOUND", "NOT_IMPLEMENTED", "PARTIAL", "PASS", "PASS", "PASS", "PASS", "PASS", "PASS", "PARTIAL", "CommercialDocumentActions.EnviarWhatsAppArquivo (wa.me local)", "LOW", "Conectar API WhatsApp Cloud"],
        ["Integrações Externas", "TEF / Pagamento Cartao em Maquininha", "NOT FOUND", "NOT FOUND", "NOT FOUND", "NOT FOUND", "NOT FOUND", "NOT FOUND", "NOT_IMPLEMENTED", "NOT_IMPLEMENTED", "NOT TESTED", "NOT TESTED", "NOT TESTED", "NOT_APPLICABLE", "NOT_APPLICABLE", "NOT FOUND", "NOT_IMPLEMENTED", "Sem SDK TEF SiTef/Scope", "MEDIUM", "Integrar TEF dedicado para varejo"],
        ["Integrações Externas", "Gateway Pix / Boleto / Cartao Online", "NOT FOUND", "NOT FOUND", "NOT FOUND", "NOT FOUND", "NOT FOUND", "NOT FOUND", "NOT_IMPLEMENTED", "NOT_IMPLEMENTED", "NOT TESTED", "NOT TESTED", "NOT TESTED", "NOT_APPLICABLE", "NOT_APPLICABLE", "NOT FOUND", "NOT_IMPLEMENTED", "Sem conexao Stripe, MercadoPago, etc.", "MEDIUM", "Planejar integracao gateway online"],
        ["Integrações Externas", "Email SMTP Envio Automatico", "NOT FOUND", "NOT FOUND", "NOT FOUND", "NOT FOUND", "NOT FOUND", "NOT FOUND", "NOT_IMPLEMENTED", "NOT_IMPLEMENTED", "NOT TESTED", "NOT TESTED", "NOT TESTED", "NOT_APPLICABLE", "NOT_APPLICABLE", "NOT FOUND", "NOT_IMPLEMENTED", "Sem servico SMTP configurado", "LOW", "Implementar envio de PDF por email"],
        ["Integrações Externas", "Cloud Sync / Portal Web Oficina", "NOT FOUND", "NOT FOUND", "NOT FOUND", "NOT FOUND", "NOT FOUND", "NOT FOUND", "NOT_IMPLEMENTED", "NOT_IMPLEMENTED", "NOT TESTED", "NOT TESTED", "NOT TESTED", "NOT_APPLICABLE", "NOT_APPLICABLE", "NOT FOUND", "NOT_IMPLEMENTED", "Aplicacao e 100% desktop local", "HIGH", "Definir arquitetura hibrida ou sync local-cloud"],
        ["UI / Design System", "Design System Light Theme", "Themes/*.xaml", "NOT FOUND", "ThemeResourceValidationService", "NOT FOUND", "NOT FOUND", "REAL", "NOT_APPLICABLE", "REAL", "PASS", "PASS", "PASS", "PASS", "NOT_APPLICABLE", "PASS", "CORE", "Themes/Colors.Light.xaml e 25 arquivos de tema", "LOW", "Manter"],
        ["UI / Design System", "Design System Dark Theme", "Themes/*.xaml", "NOT FOUND", "ThemeResourceValidationService", "NOT FOUND", "NOT FOUND", "REAL", "NOT_APPLICABLE", "REAL", "PASS", "PASS", "PASS", "NOT_APPLICABLE", "PASS", "PASS", "CORE", "Themes/Colors.Dark.xaml e DynamicResource em 53 Views", "LOW", "Manter"]
    ]
    
    matrix_csv_path = "Docs/audit/2026-09-20/B1_PRODUCT_DISCOVERY_MATRIX.csv"
    headers = [
        "Module", "Feature", "UI", "ViewModel", "Service", "Repository", "Database", 
        "Persistence", "API", "Integration", "UnitTest", "IntegrationTest", "UITest", 
        "Light", "Dark", "RBAC", "Status", "Evidence", "Risk", "NextAction"
    ]
    with open(matrix_csv_path, "w", newline="", encoding="utf-8") as fp:
        writer = csv.writer(fp)
        writer.writerow(headers)
        writer.writerows(matrix_rows)
        
    print(f"Matrix written: {len(matrix_rows)} features recorded.")
    
    # Calculate stats
    stats = {}
    for r in matrix_rows:
        st = r[16]
        stats[st] = stats.get(st, 0) + 1
    print("Matrix Stats:", stats)
    return stats

if __name__ == "__main__":
    generate_b1_docs()
